/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kys26_webthings_video_VideoPlayer */

#ifndef _Included_com_kys26_webthings_video_VideoPlayer
#define _Included_com_kys26_webthings_video_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kys26_webthings_video_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kys26_webthings_video_VideoPlayer_play
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_kys26_webthings_video_VideoPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kys26_webthings_video_VideoPlayer_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_kys26_webthings_video_VideoPlayer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kys26_webthings_video_VideoPlayer_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
